---
# Template configuration files for {{ cookiecutter.role_name }}
{% raw %}
- name: Set SELinux booleans
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    persistent: "{{ item.persistent | default('false') }}"{% endraw %}
  loop: "{{ '{{ ' }}{{ cookiecutter.role_name }}_selinux_booleans }}"
  when:
    - ansible_selinux.status == "enabled"
    - {{ cookiecutter.role_name }}_enable_selinux
  become: true
